# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'KingfisherDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Kingfisher', '~>3.9.1'
  # Pods for KingfisherDemo

  target 'KingfisherDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KingfisherDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
